apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dev
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: kargo-gitops-demo
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/managed-by: argocd
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: addon/charts/cert-manager
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://dev-control-plane:6443
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
