apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: kargo-gitops-demo
    app.kubernetes.io/component: kargo
    app.kubernetes.io/managed-by: argocd
    environment: platform
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: addon/charts/kargo
    helm:
      values: |
        controller:
          argocd:
            namespace: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
