apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-pipeline
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: kargo-gitops-demo
    app.kubernetes.io/component: kargo-pipeline
    app.kubernetes.io/managed-by: argocd
    environment: platform
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: kargo/pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: socket-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
