apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-prod
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/Kargo-GitOps-Demo.git
    targetRevision: HEAD
    path: addon/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
