apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-dev
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: addon/dev
  destination:
    server: https://dev-control-plane:6443
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
