apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-test
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: kargo-gitops-demo
    app.kubernetes.io/component: app-of-apps
    app.kubernetes.io/managed-by: argocd
    environment: test
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: addon/test
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
