apiVersion: kro.run/v1alpha1
kind: SocketIOApp
metadata:
  name: socket-io-dev
  namespace: socket-io
spec:
  name: socket-io
  image: ximran96/node-socket:latest
  replicas: 1
  port: 3500
  servicePort: 80
  serviceType: ClusterIP
