apiVersion: v1alpha1
kind: SocketIOApp
metadata:
  name: socket-io-prod
  namespace: prod
spec:
  name: socket-io
  image: ghcr.io/socketio/socket.io:latest
  replicas: 3
  port: 3500
  servicePort: 80
  serviceType: ClusterIP
