apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-prod
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: kargo-gitops-demo
    app.kubernetes.io/component: kro
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
    targetRevision: HEAD
    path: addon/charts/kro
  destination:
    server: https://prod-control-plane:6443
    namespace: kro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
