apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: socket-io
  labels:
    kargo.akuity.io/cred-type: git
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  repoURL: https://github.com/iamimran96/kargo-gitops-demo.git
  # Replace with a GitHub personal access token (with repo scope)
  username: <your-github-username>
  password: <your-github-pat>
